# vikas yojana

In [23]:
import os
import pymysql
import pandas as pd
import random
import datetime

host = os.getenv('MYSQL_HOST')
port = os.getenv('MYSQL_PORT')
user = os.getenv('MYSQL_USER')
password = os.getenv('MYSQL_PASSWORD')
database = os.getenv('MYSQL_DATABASE')

mydb =pymysql.connect(host = 'localhost', user = 'root', password = 'prasanna@123', database = 'vikasyojana')
cursor = mydb.cursor()

def RegisterUser():
    L = []
    
    aadhar = input('Enter aadhar number : ')
    L.append(aadhar)
    
    name = input('Enter name of the user : ')
    L.append(name)
    
    age = int(input('Enter age of the user : '))
    L.append(age)
    
    addd = input("Enter address of the user : ")
    L.append(addd)
    
    ph = input('Enter phone number of the user : ')
    L.append(ph)
    
    psw=input("Enter the password :")
    cpsw=input("confirm the password :")
    while(psw!=cpsw):
        print("password doesnt match please confirm the password")
        psw=input("Enter the password :")
        cpsw=input("confirm the password :")
    L.append(psw)
    
    cand = tuple(L)
    sql = "insert into RegisterUser (aadhar, name, age, addd, ph, psw) values (%s, %s, %s, %s, %s, %s)"
    cursor.execute(sql, cand)
    mydb.commit()
    
    
def SukanyaSamriddiScheme():
    print("The details of the Sukanya Samriddi Scheme is as follows : ")
    print("------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("Rate of interest 8.0% Per Annum,calculated on yearly basis ,Yearly compounded.")
    print("Minimum INR. 250/-and Maximum INR. 1,50,000/- in a financial year.")
    print("Subsequent deposit in multiple of INR 50/- Deposits can be made in lump-sum No limit on number of deposits either in a month or in a Financial year")
    ch=input("If you want to select this option .. please press y else n")
    if ch.lower()=="y":
        print("make the min payment of rs.250 to open the account in sukanya samriddi scheme : ")
        amt=int(input("Enter the amount : "))
        
        l=[]
        ####accno int NOT NULL UNIQUE, schemename varchar(20) NOT NULL ,aadhar varchar(20) NOT NULL, amount int NOT NULL
        
        accno=0
        for i in range(6):
            accno=accno*10+random.randint(1,10)
        l.append(accno)
        
        name=input("Enter the name of the applicant : ")
        l.append(name)
        
        sname="Sukanya Samriddi Scheme"
        l.append(sname)
        
        aadhar = input('Enter aadhar number : ')
        l.append(aadhar)
        
        l.append(amt)
        
        curr_date = datetime.datetime.now().strftime('%Y-%m-%d')
        l.append(curr_date)
    
        #l.append(curdate());
        #ts = "mytable"
        #ts=""+name+"ssc"
        
        #mycursor = mydb.cursor()
        
        #sql = "create table {} (accno int,name varchar(20),amount int,aadhar varchar(20), phno int);".format(ts)
        #mycursor.execute(sql)
        #mydb.commit()

        #mycursor.execute("create table '{ts}'(accno int,name varchar(20),amount int,aadhar varchar(20), phno int);")
        
        
        
        cand = tuple(l)
        sql = "insert into schemetable1 (accno,name,schemename,aadhar,amount,date) values (%s, %s, %s, %s, %s, %s)"
        cursor.execute(sql, cand)
        mydb.commit()
        
        print("congrats --- your account has been succesfully created")
        print("your account number is : ",accno)
        
    
    else:
        runAgain()
        
def KisanVikasScheme():
    print("The details of the  Kisan Vikas Scheme is as follows : ")
    print("------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("7.5 % compounded annually")
    print("Minimum of Rs. 1000/- and in multiples of Rs. 100/- No Maximum Limit")
    
    ch=input("If you want to select this option .. please press y else n")
    if ch.lower()=="y":
        print("make the min payment of rs.250 to open the account in Kisan Vikas Scheme : ")
        amt=int(input("Enter the amount : "))
        while(amt!=250):
            print("The amount is 250 --- please enter rs.250 only")
            amt=int(input("Enter the amount : "))
            
        l=[]
        
        accno=0
        for i in range(6):
            accno=accno*10+random.randint(1,10)
        l.append(accno)
        
        name=input("Enter the name of the applicant : ")
        l.append(name)
        
        sname="Kisan Vikas Scheme"
        l.append(sname)
        
        aadhar = input('Enter aadhar number : ')
        l.append(aadhar)
        
        l.append(amt)
        
        curr_date = datetime.datetime.now().strftime('%Y-%m-%d')
        l.append(curr_date)
        
        #l.append(GETDATE());
        
        cand = tuple(l)
        sql = "insert into schemetable1 (accno,name,schemename,aadhar,amount,date) values (%s, %s, %s, %s, %s, %s)"
        cursor.execute(sql, cand)
        mydb.commit()
        
        print("congrats --- your account has been succesfully created")
        print("your account number is : ",accno)
        
    
    else:
        runAgain()
        
        
def AddAmount():
    accno=int(input("please enter the account number : "))
    m=0
    tsql = "select schemename from schemetable1 where accno = %s"
    r  = (accno,)
    cursor.execute(tsql, r)
    tres = cursor.fetchall()
    for x in tres:
        sname=x[0]
        if sname=="Sukanya Samriddi Scheme":
            print("The Min Amount is 250 and max amount is 150000")
            m=int(input("please enter the amount that you wanna deposit : "))
            while(m<250 or m>150000):
                print("Please Enter Amount in between 250 and 150000 only")
                m=int(input("please enter the amount that you wanna deposit : "))
        elif sname=="Kisan Vikas Scheme":
            print("The Min Amount is 1000 and max amount is your choice ")
            m=int(input("please enter the amount that you wanna deposit : "))
            while(m<1000):
                print("Please Enter Amount greater than or 1000")
                m=int(input("please enter the amount that you wanna deposit : "))
            
                
    #s   = int(input("Enter enroll no : "))
    #r  = (accno,)
    sql = "select amount from schemetable1 where accno = %s"
    cursor.execute(sql, r)
    res = cursor.fetchall()
    for x in res:
        #print(x)
        t=x[0]#250
        t=t+m#750
        #print(type(t))
        amount=t#750
        #print(amount)
        #print(type(amount))
        
        sql = "UPDATE schemetable1 SET amount = %s WHERE accno = accno"
        cursor.execute(sql, amount)
        
        #sql="UPDATE schemetable1 SET amount = %s WHERE accno = accno"
        #sql="UPDATE schemetable1 SET amount = temp"
        #cursor.execute(sql, amount)
        #t=t+m
        #sql="UPDATE schemetable1 SET amount = amount WHERE accno = %s"
        #cursor.execute(sql, r)
        

def withdrawamount():
    accno=int(input("please enter the account number : "))
    m=int(input("please enter the amount that you wanna withdraw : "))
    
    tsql = "select amount from schemetable1 where accno = %s"
    r  = (accno,)
    cursor.execute(tsql, r)
    tres = cursor.fetchall()
    for x in tres:
        balanceamount=x[0]
        #print(balanceamount)
        #print(type(balanceamount))
        if m>balanceamount:
            print("Insufficient balance --- please give the valid amount to withdraw")
            print("your account balance is  :  ",balanceamount)
            runAgain()
        else:
            tempsql="select schemename,date from schemetable1 where accno = %s"
            r  = (accno,)
            cursor.execute(tempsql, r)
            tempres = cursor.fetchall()
            for y in tempres:
                
                k = y[0]
                fetched_dt = y[1]
                curr_date = datetime.datetime.now().date()
                #fetched_date = datetime.datetime.strptime(fetched_dt, '%Y-%m-%d').date()
                days_diff = (curr_date - fetched_dt).days
                
                #A = P(1 + 0.075)^t.
                #print(days_diff)
                
                #k = y[0]
                #fetched_dt = y[1]
                #curr_date = datetime.datetime.now().strftime('%Y-%m-%d')
                #days_diff = (curr_date - fetched_dt).days
                #print(days_diff)
                
                #k=y[0]
                #print(k)
                #fetched_dt=y[1]
                #curr_date = datetime.datetime.now().strftime('%Y-%m-%d')
                #print(type(dt))
                
                if k=="Kisan Vikas Scheme":
                    A = int(balanceamount*(1 + 0.075))^(days_diff//365)
                    #setsql=""
                    setsql = "UPDATE schemetable1 SET amount = %s WHERE accno = accno"
                    cursor.execute(setsql, A)
                    
                    ttsql = "select amount from schemetable1 where accno = %s"
                    r  = (accno,)
                    cursor.execute(tsql, r)
                    ttres = cursor.fetchall()
                    for tt in ttres:
                        ttbalanceamount=tt[0]
                        tempamount=balanceamount-m
                        tttsql = "UPDATE schemetable1 SET amount = %s WHERE accno = accno"
                        cursor.execute(tttsql, tempamount)
                        
                    
                    
                    
                elif k=="Sukanya Samriddi Scheme":
                    #A = P(1 + 0.08)^t.
                    A = int(balanceamount*(1 + 0.08))^(days_diff//365)
                    #A = balanceamount(1 + 0.075)^days_diff/365
                    #setsql=""
                    setsql = "UPDATE schemetable1 SET amount = %s WHERE accno = accno"
                    cursor.execute(setsql, A)
                    
                    ttsql = "select amount from schemetable1 where accno = %s"
                    r  = (accno,)
                    cursor.execute(tsql, r)
                    ttres = cursor.fetchall()
                    for tt in ttres:
                        ttbalanceamount=tt[0]
                        tempamount=balanceamount-m
                        tttsql = "UPDATE schemetable1 SET amount = %s WHERE accno = accno"
                        cursor.execute(tttsql, tempamount)
                
            
            #tempamount=balanceamount-m
            #sql = "UPDATE schemetable1 SET amount = %s WHERE accno = accno"
            #cursor.execute(sql, tempamount)
            #sql = "select amount from schemetable1 where accno = %s"
            #cursor.execute(sql, r)
            #res = cursor.fetchall()
            #for x in res:
                
            
            
def SeeBalance():
    accno=int(input("please enter the account number : "))
    r  = (accno,)
    sql = "select amount from schemetable1 where accno = %s"
    cursor.execute(sql, r)
    res = cursor.fetchall()
    for x in res:
        print(" The Balance in your Account with the account number ",accno," is : ",x[0])
    
    
    
def selectscheme():
    print("Please select the scheme below : ")
    print("Enter 1 : Sukanya Samriddi Scheme")
    print("Enter 2 : Kisan Vikas Scheme")
    
    try:
        userInput = int(input("Please select an above option: "))
    except ValueError:
        exit("Hey! That is not a number")
    else:
        print("\n")
        if(userInput == 1):
            SukanyaSamriddiScheme()
        elif (userInput==2):
            KisanVikasScheme()
        
        
    
def deleteaccount():
    s=int(input("Enter aadhar number of the user to be deleted : "))
    r=(s,)
    sql="delete from RegisterUser where aadhar = %s"
    cursor.execute(sql,r)
    mydb.commit()
    print("The user with the aadhar number",s,"is removed.")
    
def MenuSet():
    print("Enter 1 : To Register user")
    print("Enter 2 : To select scheme ")
    print("Enter 3 : To delete account")
    print("Enter 4 : Add Amount to your Account")
    print("Enter 5 : See balance")
    print("Enter 6 : withdraw amount")
    
    try:
        userInput = int(input("Please select an above option: "))
    except ValueError:
        exit("Hey! That is not a number")
    else:
        print("\n")
        if(userInput == 1):
            RegisterUser()
        elif (userInput==2):
            selectscheme()
        elif (userInput==3):
            deleteaccount()
        elif (userInput==4):
            AddAmount()
        elif (userInput==5):
            SeeBalance()
        elif (userInput==6):
            withdrawamount()
            
MenuSet()

def runAgain():
    runAgn = input("want To Run Again Y/n: ")
    while (runAgn.lower() == 'y'):
        MenuSet()
        runAgn = input("\nwant To Run Again Y/n: ")
runAgain()

Enter 1 : To Register user
Enter 2 : To select scheme
Enter 3 : To delete account
Enter 4 : Add Amount to your Account
Enter 5 : See balance
Enter 6 : withdraw amount
Please select an above option: 5


please enter the account number : 846533
want To Run Again Y/n: n

In [30]:
print(len("Sukanya Samriddi Scheme"))

23

In [65]:
t=(10,20,30)
print(t[0])

10

In [ ]:
#for login
def userlogin():
    
    ladhar=int(input("Enter the adhar number :"))
    lpsw=input("Enter the password :")
    
    
    
    while(adhar!=ladhar or psw!=lpsw):
        print("invalid credentials try to login again")
        ladhar=int(input("Enter the adhar number :"))
        lpsw=input("Enter the password :")